FROM node:25-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npx vite build

FROM nginx:1.29.8-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
